//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingEntities : DbContext
    {
        public BookingEntities()
            : base("name=BookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingSeatMapping> BookingSeatMappings { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieBooking> MovieBookings { get; set; }
        public virtual DbSet<MTSMapping> MTSMappings { get; set; }
        public virtual DbSet<ShowTiming> ShowTimings { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Theatre> Theatres { get; set; }
    }
}
