//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSeatMapping
    {
        public int BookingShowSeatMappingId { get; set; }
        public Nullable<int> BookingId { get; set; }
        public string SeatNo { get; set; }
        public Nullable<int> RowNo { get; set; }
        public Nullable<int> ColumnNo { get; set; }
    
        public virtual MovieBooking MovieBooking { get; set; }
    }
}
