//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theatre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Theatre()
        {
            this.MTSMappings = new HashSet<MTSMapping>();
        }
    
        public int TheatreId { get; set; }
        public string TheatreName { get; set; }
        public int Rows { get; set; }
        public int SeatsPerRows { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int NoOfSeats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MTSMapping> MTSMappings { get; set; }
    }
}
